base_url = "https://svnscha.github.io"
title = "svnscha"
generate_feed = true
minify_html = true
compile_sass = true
build_search_index = false
theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "two-dark"

[extra]
use_cdn = false
theme = "dark"
mathjax = true
footer = "Copyright © 2024 Sven Scharmentke. All rights reserved."

menu = [
    { name = "/about", url = "/about", weight = 1 },
]

socials = [
    { name = "linkedin", url = "https://www.linkedin.com/in/svnscha/", icon = "linkedin" },
    { name = "github", url = "https://github.com/svnscha/", icon = "github" },
]
